version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value: /app/static/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/static/
    depends_on:
      - web

volumes:
  static_value: