# Generated by Django 5.0.2 on 2024-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0004_alter_item_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='USD', max_length=3, verbose_name='Валюта заказа'),
        ),
    ]
